//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamGameWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Payment
    {
        public int Payment_Id { get; set; }
        public int Payment_Amount { get; set; }
        public string Payment_Desc { get; set; }
        public Nullable<int> Payment_Mode { get; set; }
        public Nullable<int> Transaction_Refrence_Id { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> Amount_Transfer { get; set; }
        public string To { get; set; }
        public string From { get; set; }
        public Nullable<int> Transaction_status { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_MasterTable M_MasterTable { get; set; }
    }
}
