//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamGameWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User_Contest
    {
        public int Contest_Id { get; set; }
        public int User_Id { get; set; }
        public string Contest_Description { get; set; }
        public string Match_Info { get; set; }
        public string ModifiedBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_Contest_Master M_Contest_Master { get; set; }
    }
}
